name: attendanceapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter_riverpod: ^2.6.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  email_validator: ^3.0.0
  flutter_spinkit: ^5.2.1
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true

 