// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaLiMTRVPAKUz3v90ZjhfkXPARKhwu_WI',
    appId: '1:193846145104:web:683fc28c4f1734492e6155',
    messagingSenderId: '193846145104',
    projectId: 'attedance-2b596',
    authDomain: 'attedance-2b596.firebaseapp.com',
    storageBucket: 'attedance-2b596.firebasestorage.app',
    measurementId: 'G-EWGCF8R679',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIbsh_wbqexOxQBgo-PFjpo5kvH2pWdw',
    appId: '1:193846145104:android:c90080daccd11bb92e6155',
    messagingSenderId: '193846145104',
    projectId: 'attedance-2b596',
    storageBucket: 'attedance-2b596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsD2mcgAGIY-LdZLKxayRvF066T1MZz2E',
    appId: '1:193846145104:ios:354d9220944a63122e6155',
    messagingSenderId: '193846145104',
    projectId: 'attedance-2b596',
    storageBucket: 'attedance-2b596.firebasestorage.app',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsD2mcgAGIY-LdZLKxayRvF066T1MZz2E',
    appId: '1:193846145104:ios:354d9220944a63122e6155',
    messagingSenderId: '193846145104',
    projectId: 'attedance-2b596',
    storageBucket: 'attedance-2b596.firebasestorage.app',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaLiMTRVPAKUz3v90ZjhfkXPARKhwu_WI',
    appId: '1:193846145104:web:84e72adf3c68378c2e6155',
    messagingSenderId: '193846145104',
    projectId: 'attedance-2b596',
    authDomain: 'attedance-2b596.firebaseapp.com',
    storageBucket: 'attedance-2b596.firebasestorage.app',
    measurementId: 'G-9Z108DKGL0',
  );

}