// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxOFFURF-bh37Y6iAQ6ZBK51zkM25ZZc',
    appId: '1:793224950657:web:1d5a71bdcd0bc75829ee80',
    messagingSenderId: '793224950657',
    projectId: 'attendance-c4b89',
    authDomain: 'attendance-c4b89.firebaseapp.com',
    databaseURL: 'https://attendance-c4b89-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'attendance-c4b89.firebasestorage.app',
    measurementId: 'G-XPFYZ3NQGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPy-ArpB1jDhXgDIxpzJ6iHT92yZlUxuc',
    appId: '1:793224950657:android:716ef732b5d82a1929ee80',
    messagingSenderId: '793224950657',
    projectId: 'attendance-c4b89',
    databaseURL: 'https://attendance-c4b89-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'attendance-c4b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-uME4a9UVV_iEv9cHq4RF0pCW_9WqrA',
    appId: '1:793224950657:ios:dcce3c5bd8dcf6d329ee80',
    messagingSenderId: '793224950657',
    projectId: 'attendance-c4b89',
    databaseURL: 'https://attendance-c4b89-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'attendance-c4b89.firebasestorage.app',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-uME4a9UVV_iEv9cHq4RF0pCW_9WqrA',
    appId: '1:793224950657:ios:dcce3c5bd8dcf6d329ee80',
    messagingSenderId: '793224950657',
    projectId: 'attendance-c4b89',
    databaseURL: 'https://attendance-c4b89-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'attendance-c4b89.firebasestorage.app',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxOFFURF-bh37Y6iAQ6ZBK51zkM25ZZc',
    appId: '1:793224950657:web:02d9bdacb33d9c5029ee80',
    messagingSenderId: '793224950657',
    projectId: 'attendance-c4b89',
    authDomain: 'attendance-c4b89.firebaseapp.com',
    databaseURL: 'https://attendance-c4b89-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'attendance-c4b89.firebasestorage.app',
    measurementId: 'G-PXYCPF55GY',
  );
}
